# Clean, modern spacing
gaps inner 4

# Keep minimal borders for separation
default_border pixel 1

# Swayfx
corner_radius 5
shadows enable
blur enable

layer_effects "wofi" blur enable
layer_effects "wwwidgets" {
    blur enable
    corner_radius 5
}
layer_effects "wlogout" blur enable
