gaps inner 10
gaps outer 5
smart_gaps on 

default_border pixel 2
default_floating_border pixel 2

corner_radius 10
shadows on
shadow_blur_radius 20
shadow_color #00000070

blur on
blur_xray off
blur_passes 2
blur_radius 4

client.focused          #BD93F9 #BD93F9 #282A36 #BD93F9   #BD93F9
client.focused_inactive #44475A #44475A #F8F8F2 #44475A   #44475A
# client.unfocused        #282A36 #282A36 #BFBFBF #282A36   #282A36
client.urgent           #FF5555 #FF5555 #F8F8F2 #FF5555   #FF5555
client.placeholder      #282A36 #282A36 #F8F8F2 #282A36   #282A36
client.background       #F8F8F2

seat seat0 xcursor_theme Adwaita

layer_effects "wofi" blur enable; shadows enable; corner_radius 10
layer_effects "wwwidgets" {
    blur enable
}

layer_effects "wlogout" blur enable
